services:
  db:
    image: postgres
    hostname: db
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=match_user
      - POSTGRES_PASSWORD=match_password
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data 

  rabbitmq1:
    image: rabbitmq:4-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./security/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - D:/rabbit_data/data1:/var/lib/rabbitmq
      - D:/rabbit_data/logs1:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq2:
    image: rabbitmq:4-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./security/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - D:/rabbit_data/data2:/var/lib/rabbitmq
      - D:/rabbit_data/logs2:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq3:
    image: rabbitmq:4-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./security/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - D:/rabbit_data/data3:/var/lib/rabbitmq
      - D:/rabbit_data/logs3:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936
    networks:
      - rabbitmq

  redis:
    image: redis:8.0-M02-alpine3.20
    hostname: redis-server
    container_name: redis-server
    ports:
    - "63079:6379"

networks:
  rabbitmq:

volumes:
  pgdata: